title: Nathan Alakija # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 



  <a href="https://www.linkedin.com/in/nathanalakija/">LinkedIn</a> 
  <br>
  <a href="https://bowen.finance/cv/" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://bowen.finance/" class="btn btn--info">Portfolio</a>  
  <br>
  <a href="https://www.GitHub.com/nalakija/">GitHub</a>  
  <br>

  
theme: jekyll-theme-minimal
